---
description: コンパイラの警告 (レベル 2) CS0162
title: コンパイラの警告 (レベル 2) CS0162
ms.date: 07/20/2015
f1_keywords:
- CS0162
helpviewer_keywords:
- CS0162
ms.assetid: 369b5b02-a9cc-404b-b758-4184285af2de
ms.openlocfilehash: 584faebca993de75c6e02f0b3d885fa547be8cea
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: HT
ms.contentlocale: ja-JP
ms.lasthandoff: 02/14/2021
ms.locfileid: "100424294"
---
# <a name="compiler-warning-level-2-cs0162"></a>コンパイラの警告 (レベル 2) CS0162

到達できないコードが検出されました
  
実行されないコードが検出されました。

## <a name="example"></a>例

次の例では CS0162 が生成されます。

```csharp
// CS0162.cs
// compile with: /W:2
public class Program
{
    public static void Main()
    {
        goto lab1;
        {
            // The following statements cannot be reached:
            int i = 9;   // CS0162
            i++;
        }
    lab1:
        {
        }
    }
}
```

このエラーが生成されるもう 1 つの一般的な例を次に示します。

```csharp
public static class Class1
{
    public static string Method1()
    {
        string x = "a";
        switch (x)
        {
            case "a":
                return "a";
                break;          // CS0162
        }
        return "";
    }
}
```

`return` ステートメントの後に発生するため、`break` ステートメントに到達できません。
`return` ステートメントは、囲まれている `case` 分岐で終了します。
