---
title: 破損状態の例外に対するコード分析規則 CA2153 (コード分析)
description: 破損状態の例外に対するコード分析規則 CA2153 について
ms.date: 02/19/2019
ms.topic: reference
author: gewarren
ms.author: gewarren
ms.openlocfilehash: 32d9c6ef19d0cf1fa869f21cff7dc90d95c44277
ms.sourcegitcommit: 05d0087dfca85aac9ca2960f86c5efd218bf833f
ms.translationtype: HT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/30/2021
ms.locfileid: "99714873"
---
# <a name="ca2153-avoid-handling-corrupted-state-exceptions"></a>CA2153:破損状態の例外の処理を回避する

| | 値 |
|-|-|
| **ルール ID** |CA2153|
| **カテゴリ** |[Security](security-warnings.md)|
| **修正が中断か中断なしであるか** |なし|

## <a name="cause"></a>原因

[破損状態例外 (CSE)](/archive/msdn-magazine/2009/february/clr-inside-out-handling-corrupted-state-exceptions) は、メモリの破損がプロセス内に存在していることを示します。 プロセスをクラッシュさせるのではなくこれらの例外をキャッチすることは、攻撃者が破損したメモリ領域にセキュリティ上の弱点を見出すことができた場合に、セキュリティ上の脆弱性となる可能性があります。

## <a name="rule-description"></a>規則の説明

CSE は、プロセスが破損状態にあり、システムによってキャッチされていないことを示します。 破損した状態のシナリオでは、<xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute?displayProperty=fullName> 属性でメソッドをマークした場合に、汎用ハンドラーのみがこの例外をキャッチします。 既定では、[共通言語ランタイム (CLR)](../../../standard/clr.md) は、CSE の catch ハンドラーを呼び出しません。

最も安全な方法は、この種の例外をキャッチせずにプロセスをクラッシュさせることです。 コードをログに記録しても、攻撃者はメモリ破損のバグを悪用できます。

`catch (System.Exception e)` や例外パラメーターを持たない `catch` などすべての例外をキャッチする汎用ハンドラーを使用して CSE をキャッチすると、この警告がトリガーされます。

## <a name="how-to-fix-violations"></a>違反の修正方法

この警告を解決するには、次のいずれかの操作を行います:

- <xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute> 属性を削除してください。 これにより、CSE を catch ハンドラーに渡さない既定の実行時の動作に戻ります。

- 特定の例外の種類をキャッチするハンドラーではなく汎用 catch ハンドラーを削除します。 ハンドラー コードが安全に処理できたと仮定した場合 (まれ)、これに CSE が含まれることがあります。

- 例外を呼び出し元に渡し、実行中のプロセスを終了させる catch ハンドラーで CSE を再スローします。

## <a name="when-to-suppress-warnings"></a>どのようなときに警告を抑制するか

この規則による警告は抑制しないでください。

## <a name="pseudo-code-example"></a>擬似コードの例

### <a name="violation"></a>違反

次の擬似コードでは、このルールにより検出されたパターンを示しています。

```csharp
[HandleProcessCorruptedStateExceptions]
// Method that handles CSE exceptions.
void TestMethod1()
{
    try
    {
        FileStream fileStream = new FileStream("name", FileMode.Create);
    }
    catch (Exception e)
    {
        // Handle exception.
    }
}
```

### <a name="solution-1---remove-the-attribute"></a>解決策 1 - 属性を削除する

<xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute> 属性を削除すると、メソッドによって破損状態の例外が処理されなくなります。

```csharp
void TestMethod1()
{
    try
    {
        FileStream fileStream = new FileStream("name", FileMode.Create);
    }
    catch (Exception e)
    {
        // Handle exception.
    }
}
```

### <a name="solution-2---catch-specific-exceptions"></a>解決策 2 - 特定の例外をキャッチする

汎用 catch ハンドラーを削除し、特定の例外の種類のみをキャッチします。

```csharp
void TestMethod1()
{
    try
    {
        FileStream fileStream = new FileStream("name", FileMode.Create);
    }
    catch (IOException e)
    {
        // Handle IOException.
    }
    catch (UnauthorizedAccessException e)
    {
        // Handle UnauthorizedAccessException.
    }
}
```

### <a name="solution-3---rethrow"></a>解決策 3 - 再スローする

例外を再スローします。

```csharp
[HandleProcessCorruptedStateExceptions]
void TestMethod1()
{
    try
    {
        FileStream fileStream = new FileStream("name", FileMode.Create);
    }
    catch (Exception e)
    {
        // Rethrow the exception.
        throw;
    }
}
```
