---
description: "詳細情報: 'Catch' を 'Try' ステートメント内にある 'Finally' の後に置くことはできません"
title: "'Catch' を 'Try' ステートメント内にある 'Finally' の後に置くことはできません"
ms.date: 07/20/2015
f1_keywords:
- vbc30379
- bc30379
helpviewer_keywords:
- BC30379
ms.assetid: 33d1278b-cf10-4c66-aaf8-08a4372f370b
ms.openlocfilehash: ec177fadf2490c3779e0ad3a1f754319e12bd9cc
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: HT
ms.contentlocale: ja-JP
ms.lasthandoff: 02/14/2021
ms.locfileid: "100454951"
---
# <a name="catch-cannot-appear-after-finally-within-a-try-statement"></a>'Catch' を 'Try' ステートメント内にある 'Finally' の後に置くことはできません

コード内で `Catch` ステートメントが、 `Finally` ステートメント ブロックの末尾の `Try` の後にあります。 `Catch` は `Try...Catch...Finally` ステートメント ブロック内に置く必要があります。  
  
 **エラー ID:** BC30379  
  
## <a name="to-correct-this-error"></a>このエラーを解決するには  
  
1. `Catch` ステートメントをコード内の適切な場所に移動します。  
  
## <a name="see-also"></a>関連項目

- [Try...Catch...Finally ステートメント](../language-reference/statements/try-catch-finally-statement.md)
