---
description: 詳細については、' Finally ' を ' Try ' ステートメントの外側に記述することはできません
title: "'Finally' を 'Try' ステートメントの外に置くことはできません。"
ms.date: 07/20/2015
f1_keywords:
- vbc30382
- bc30382
helpviewer_keywords:
- BC30382
ms.assetid: 0314d8d2-18bc-4bbd-858c-0a18408b52fd
ms.openlocfilehash: 5255cf3e99faf019ce8313f75425cf18b9c9d80d
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 02/14/2021
ms.locfileid: "100472164"
---
# <a name="finally-cannot-appear-outside-a-try-statement"></a>'Finally' を 'Try' ステートメントの外に置くことはできません。

`Finally` は `Try...Catch...Finally` ブロックを終了するために使用します。そのため、ブロックの最後で 1 回のみ出現できます。 不要な `Finally`ステートメントがあるか、または `Finally` ステートメントが、対応する `Try` ブロックの境界の外側にあります。  
  
 **エラー ID:** BC30382  
  
## <a name="to-correct-this-error"></a>このエラーを解決するには  
  
1. 不要な `Finally` ステートメントを見つけて削除します。  
  
2. `Finally` ステートメントをコード内の適切な場所に移動します。  
  
## <a name="see-also"></a>関連項目

- [Try...Catch...Finally ステートメント](../language-reference/statements/try-catch-finally-statement.md)
