---
description: 詳細については、' Catch ' を ' Try ' ステートメントの外側に記述することはできません
title: "'Catch' を 'Try' ステートメントの外に置くことはできません"
ms.date: 07/20/2015
f1_keywords:
- bc30380
- vbc30380
helpviewer_keywords:
- BC30380
ms.assetid: 73ce950d-881f-4532-8024-40a4930abd32
ms.openlocfilehash: 4ac18a51602c7dc5c4d7b397e1b64f9ed77fcc87
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 02/14/2021
ms.locfileid: "100473902"
---
# <a name="catch-cannot-appear-outside-a-try-statement"></a>'Catch' を 'Try' ステートメントの外に置くことはできません

`Catch` は `Try...Catch...Finally` ステートメント ブロック内に置く必要があります。 不要な `Catch` ステートメントが `Try` ブロック内にあるか、または `Catch` ステートメントが、対応する `Try` ブロックの境界の外側にあります。  
  
 **エラー ID:** BC30380  
  
## <a name="to-correct-this-error"></a>このエラーを解決するには  
  
1. 不要な場合は `Catch` ステートメントを削除します。または、 `Try...Catch...Finally` ステートメント ブロック内に置きます。  
  
## <a name="see-also"></a>関連項目

- [Try...Catch...Finally ステートメント](../language-reference/statements/try-catch-finally-statement.md)
