---
description: 詳細については、' Catch ' ブロックに到達していません。 <exception> 同じ ' Try ' ステートメントで上の処理が行われています
title: "'Catch' ブロックに到達しませんでした。'<exception>' は、同じ Try ステートメントで処理しました。"
ms.date: 07/20/2015
f1_keywords:
- bc42031
- vbc42031
helpviewer_keywords:
- BC42031
ms.assetid: 7d15597c-5988-42ea-a853-63cbf78faaf3
ms.openlocfilehash: fc52c21f7a319c26b6ca7128c8d2d781db1a58c1
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 02/14/2021
ms.locfileid: "100473022"
---
# <a name="catch-block-never-reached-exception-handled-above-in-the-same-try-statement"></a>'Catch' ブロックに到達しませんでした。'\<exception>' は、同じ Try ステートメントで処理しました。

先行する `Catch` ブロックで処理されるため、コードの `Try` ブロックには到達できません。  
  
既定では、このメッセージは警告です。 警告を非表示にする方法や、警告をエラーとして扱う方法の詳細については、「 [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic)」をご覧ください。
  
 **エラー ID:** BC42031  
  
## <a name="to-correct-this-error"></a>このエラーを解決するには  
  
- 不要なステートメントを削除します。  
  
## <a name="see-also"></a>関連項目

- [Try ブロックと Catch ブロックを使用して例外をキャッチする方法](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [ユーザー フィルター例外ハンドラーの使用](../../standard/exceptions/using-user-filtered-exception-handlers.md)
- [Try...Catch...Finally ステートメント](../language-reference/statements/try-catch-finally-statement.md)
